local fileTypes = {
    unknown = "Plain text",

    ada = "Ada",
	apacheconf = "Apache",
	asm = "Assembly",
	batch = "Batch",
	c = "C",
	caddyfile = "Caddy",
	clojure = "Clojure",
	cmake = "CMake",
	coffeescript = "CoffeeScript",
	["c++"] = "C++",
	crystal = "Crystal",
	csharp = "C#",
	css = "CSS",
	cuda = "CUDA",
	d = "D",
	dart = "Dart",
	dockerfile = "Docker",
	elixir = "Elixir",
	elm = "Elm",
	erlang = "Erlang",
	fish = "Shell Script (fish)",
	forth = "FORTH",
	fortran = "Fortran",
	fsharp = "F#",
	gdscript = "GDScript",
	["git-commit"] = "Git Commit Message",
	["git-config"] = "Git Config",
	["git-rebase-todo"] = "Git Rebase Message",
	glsl = "GLSL",
	go = "Go",
	groovy = "Groovy",
	haskell = "Haskell",
	html = "HTML",
	ini = "Ini",
	java = "Java",
	javascript = "JavaScript",
	json = "JSON",
	jsx = "JavaScript (JSX)",
	julia = "Julia",
	kotlin = "Kotlin",
	log = "Log",
	lua = "Lua",
	makefile = "Makefile",
	markdown = "Markdown",
	nginx = "NGINX",
	nim = "Nim",
	nix = "Nix",
	nu = "Shell Script (Nushell)",
	["objective-c"] = "Objective-C",
	ocaml = "OCaml",
	odin = "Odin",
	pascal = "Pascal",
	perl = "Perl",
	php = "PHP",
	powershell = "PowerShell",
	python2 = "Python 2",
	python = "Python",
	r = "R",
	raku = "Raku",
	rst = "reStructuredText",
	ruby = "Ruby",
	rust = "Rust",
	scala = "Scala",
	shell = "Shell Script",
	smalltalk = "Smalltalk",
	solidity = "Solidity",
	sql = "SQL",
	svelte = "Svelte",
	swift = "Swift",
	tcl = "Tcl",
	terraform = "Terraform",
	tex = "TeX",
	toml = "TOML",
	typescript = "TypeScript",
	v = "V",
	verilog = "Verilog",
	vhdl = "VHDL",
	vue = "Vue",
	xml = "XML",
	yaml = "YAML",
	zig = "Zig",
	zsh = "Shell Script (zsh)",

	ino = "arduino",
	erb = "eruby",
}

local function getLanguage(fileType)
	if fileTypes[fileType] ~= nil then
		return fileTypes[fileType]
	end

	return fileType
end

return getLanguage